// scripts/build.mjs — no dependencies (Node >= 22.13).
//
//   node scripts/build.mjs           regenerates the generated files
//   node scripts/build.mjs --check   fails if they're out of date (CI)
//
// Generated files (never edit by hand):
//   dist/morph-core.js          core/morph-core.ts with types stripped, for the web page
//   conformance/fixtures.json   expected results for every transition, checked by every port
//
// The fixtures embed their own copy of the data: they only need regenerating
// when the ENGINE changes, not when designers edit morph-icons.json.

import { stripTypeScriptTypes } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const coreSrc = readFileSync(join(root, 'core/morph-core.ts'), 'utf8');
const header = '// GENERATED by scripts/build.mjs from core/morph-core.ts — do not edit.\n';
const coreJs = header + stripTypeScriptTypes(coreSrc);

// Fixtures are computed with the freshly generated JS (written to a temp file
// so --check never touches dist/).
const tmp = join(root, 'dist', '.fixtures-tmp.mjs');
mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(tmp, coreJs);
const core = await import(pathToFileURL(tmp).href);
rmSync(tmp);

const data = JSON.parse(readFileSync(join(root, 'morph-icons.json'), 'utf8'));
// A forced override, so the fixtures cover that path (and its inverse).
data.overrides = { ...(data.overrides ?? {}), 'menu>check': { map: [2, 0, 1], flip: [false, true, false] } };

const r = (n) => Math.round(n * 1e6) / 1e6;
const segOut = (s) => [r(s.x1), r(s.y1), r(s.x2), r(s.y2), r(s.o)];
const frameOut = (f) => ({ rotation: r(f.rotation), lines: f.lines.map(segOut) });
const SAMPLES = [0.3, 0.5];

const names = Object.keys(data.icons);
const transitions = [];
for (const a of names) {
  for (const b of names) {
    if (a === b) continue;
    const p = core.plan(data, core.restState(data, a), b);
    const entry = { from: a, to: b, kind: p.kind };
    if (p.kind === 'rotate') Object.assign(entry, { rotFrom: r(p.from), rotTo: r(p.to) });
    if (p.kind === 'morph') Object.assign(entry, { map: p.map, flip: p.flip, source: p.source });
    entry.frames = SAMPLES.map((t) => ({ t, ...frameOut(core.frameAt(p, t)) }));
    transitions.push(entry);
  }
}

// Interruptions: a -> b, cut at `cut`, then -> c. Checks stateAt + replanning.
const chains = [
  ['menu', 'play', 'pause', 0.4],
  ['arrow-up', 'arrow-right', 'arrow-down', 0.5],
  ['arrow-right', 'arrow-down', 'chevron-left', 0.6],
  ['plus', 'cross', 'minus', 0.3],
  ['check', 'chevron-down', 'more', 0.7],
].map(([a, b, c, cut]) => {
  const p1 = core.plan(data, core.restState(data, a), b);
  const mid = core.stateAt(p1, cut);
  const p2 = core.plan(data, mid, c);
  return { from: a, via: b, cut, to: c, kind: p2.kind, frames: SAMPLES.map((t) => ({ t, ...frameOut(core.frameAt(p2, t)) })) };
});

const fixtures = {
  about: 'Expected engine results. Every port must reproduce them within 1e-4. Regenerate: node scripts/build.mjs',
  tolerance: 1e-4,
  data,
  ease: [0, 0.1, 0.25, 0.5, 0.75, 0.9, 1].map((t) => [t, r(core.ease(t))]),
  shortestDelta: [[0, 90], [270, 0], [0, 270], [90, 270], [270, 90], [45, 0], [315, 90], [0, 180], [180, 0], [-90, 450]].map(
    ([a, b]) => [a, b, r(core.shortestDelta(a, b))],
  ),
  transitions,
  chains,
};
const fixturesJson = JSON.stringify(fixtures) + '\n';

const outputs = [
  [join(root, 'dist/morph-core.js'), coreJs],
  [join(root, 'conformance/fixtures.json'), fixturesJson],
];

let stale = 0;
for (const [file, content] of outputs) {
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    console.error(`OUT OF DATE: ${file.replace(root + '/', '')} — run: node scripts/build.mjs`);
    stale++;
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${file.replace(root + '/', '')}`);
  }
}
if (check && stale) process.exit(1);
if (check) console.log('Generated files are up to date.');
console.log(`${transitions.length} transitions, ${chains.length} interruption chains in the fixtures.`);
